### ISSUE TITLE
add SECURITY.md

### ISSUE THREAD

**Issue by Cerchie** [a11ysurf/a11y.surf#13]
Re the recs here: https://github.com/google/oss-vulnerability-guide/blob/main/guide.md#about-this-guide

Would love to hear your thoughts @BenDMyers

**Comment by BenDMyers** [comment]
Ooh, interesting. I hadn't heard of this before, @Cerchie - thank you so much for sharing!

I think a `SECURITY.md` file would be good to have — it certainly couldn't hurt! — but also, a11y.surf is a bunch of static files with no client-side input, all hosted on a CDN. I think risks are low, so I suspect our security policy should be kept short and probably just "To report a potential vulnerability or security issue, email…"

What do you think?

**Comment by Cerchie** [comment]
Sounds perfectly appropriate!

**Comment by BenDMyers** [comment]
Ah, wait! OSS packages are included in that security story!
