### ISSUE TITLE
Define "screen reader"

### ISSUE THREAD

**Issue by BenDMyers** [a11ysurf/a11y.surf#6]

**Comment by Cerchie** [comment]
working on this-- just need permission to push
 ```
`remote: Permission to a11ysurf/a11y.surf.git denied to Cerchie.
fatal: unable to access 'https://github.com/a11ysurf/a11y.surf.git/': The requested URL returned error: 403
```

**Comment by BenDMyers** [comment]
I've sent you an invite to the organization, @Cerchie. I think in the future, though, we should recommend people fork the repo and create pull requests from their fork into the a11y.surf repo.

**Comment by Cerchie** [comment]
That would be best practice! Thanks for pointing that out.
